### ISSUE TITLE
Page for code alliance

### ISSUE THREAD

**Issue by meekrosoft** [Praqma/praqma.com#430]

**Comment by jonnycoull** [comment]
![josra](https://cloud.githubusercontent.com/assets/17589853/19811256/809d4b2a-9d28-11e6-929a-dfb4e53bd5c7.png)
@meekrosoft for the small pic

**Comment by lakruzz** [comment]
@jonnycoull is that the new logo? Cool!

* We need a version in 3:4 format (height:width e.g. 600x800px)
* Is the blurred code in the background intended, it looks like it's 3 different layers of different code

**Comment by lakruzz** [comment]
@buep  said:

>I could try to put something in for the blog, but I would need some help on finishing it.
And I probably won't have time until Monday.

@buep Mike has already made some copy related to this in 6b7e111

I'll give it a review now, so you mig be off the hook - if you wanna contribute, please continue on the branch `430-Page-for-code-alliance` together with me and @meekrosoft

**Comment by jonnycoull** [comment]
Hi @lakruzz @meekrosoft no not the new one, but there's a hint of direction in there. I thought it was just a plug of that small image on the site. and yes its 3 /4 layers of code just for a bit of texture. if you'd prefer something that relates to someone that could read it feel free to paste here and ill use that code instead. and then update the size.

**Comment by lakruzz** [comment]
@jonnycoull 

Could be something like:

https://github.com/Praqma/memory-map-plugin/blob/master/src/main/java/net/praqma/jenkins/memorymap/graph/MemoryMapGraphConfiguration.java

or 

https://github.com/Praqma/memory-map-plugin/blob/master/src/main/java/net/praqma/jenkins/memorymap/MemoryMapProjectAction.java

...does it make sense? (well I know it doesn't  - but as used for background - that was what I meant.


__PLEASE NOTE:__ - This issue is closed - I need you to upload the logo in #437 instead
