### ISSUE TITLE
Staff portraits - needs to adhere to the laws of gravity

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#509]
Following up on #493 

Hmm - Quite a lot of the pictures (almost everyone) needs to be straightened up. We need to adhere to the laws of gravity

## Before (600x400)
![timea-3-before](https://cloud.githubusercontent.com/assets/155492/20858706/b7bdc42e-b94b-11e6-8a3a-a77e099831dc.png)

## After (573x382)
![timea-3-after](https://cloud.githubusercontent.com/assets/155492/20858705/b7bd11aa-b94b-11e6-80c8-ea302d3832b9.jpg)

In the process we loose pixels, so it's something that needs to be done _before_ we crop.

@MarieLKruse already did this in the original batch of pic that was forwarded, ...but that batch was discarded because they we not in in RAW format, now - at the end of a long process - we end up in a `png` format which is less than the desired 600x400 (573x382) and we had both @MarieLKruse, @jonnycoull, @illus0r and now even @lakruzz tamper with the images.

I don't like this process - it's inefficient and expensive (since all of you are invoicing me your time)

I think The process that works well (best) would be something like:

1. Art Director ( @jonnycoull ) and Photographer ( @MarieLKruse ) agrees on what format is to be delivered (`Raw|Compressed` + minimum size)
2. Photographer shoots portraits, selects to ones that are useful and _does the first level of image manipulation_ (adjusting colors, contrasts, level horizon) This is the RAW set that's delivered.
3. The RAW set is stored in an archive (I'd prefer a Lightroom solution accessible by both Praqma and Phable - but for now  we are using the [Praqma.design/Staff-portraits](https://drive.google.com/drive/folders/0BwzcaooBNQZQRzRMSHhFOURMbjg) folder on Google Drive).
4. Any level of further cropping, scaling, or _photoshopping_ takes offset in the RAW set delivered by the photographer. If this level of manipulation isn't done by the Art Director, it would be natural to delegate it back to the Photographer or a web designer.
5. The manipulated final set for the rouge gallery goes to the git repo - but _only_ the ones that are actually being used. (we don't want "dead" resources in the repo.

Please give your feedback on this process, it it acceptable to all stakeholders? 

At this point, I think we need to start over (using this process) since I can't have portraits on the web, that defies gravity.

**Comment by jonnycoull** [comment]
@lakruzz you say 600x400 is less than desired. that was the size i was supplied by yourself and ivan, im confused. what is the correct size?

**Comment by jonnycoull** [comment]
@lakruzz done and uploaded took 10mins, any tweak like this i can deal with. I know this initial process has been longer than you wanted mainly down to me wanting new shots now we've discussed and sorted that I hope things will be smoother, and apologies i didn't spot the slant in the backgrounds on my run through. though it would have been nice to have been supplied the information when you knew i would be essentially redoing them with better levels, thats why the initial batch was disregarded, along with the poses. In future im sure a proper discussion of the requirements will iron a lot of this out. 

• images to be shot, images given a rough edit (so not to supply 1000's) and put on Drive (or future selected storage device) in .raw format.
• images, along with any discussed requirements via the person requesting the job supplied to the designer. For example, my lens had some dirt files 99-130 can u remove. some o slant need straightening. 
• Designer supplies images to git, copies go on Drive of cropped and Tweaked high res jpg. ( these are files that have been processed out of the raw format and saved. not other crops or ammends. 
• any mistakes designer to tweak. 

that sound ok? 
why i disregarded the initial ones was because they were too blown out. see pic. even for the MVP as some of these will be kept as were only reshooting some of the staff. its why i need the raw and not the jags marie initially supplied as tweaking an already tweaked jpg causes too much degradation to an image. 

more than happy to show marie some tricks to help make her pics sing in the future, but for now i think it best i do it. until it can be done. 

if you happy with the amended images or spot any i missed, please let me know. I uploaded them all as when you set the "size" it will be easier to swap round instantly with pics that work. instead of waiting. 
![screen shot 2016-12-02 at 10 26 05](https://cloud.githubusercontent.com/assets/17589853/20860237/1be8722c-b96b-11e6-9a26-710c1674c466.jpg)

**Comment by lakruzz** [comment]
@jonnycoull 
>you say 600x400 is less than desired.

No, __573x382__ is less than desired; pics needs to be leveled before they are cropped, not after.
